name: Dependabot add changie file
on:
  pull_request:
    types: [opened]

jobs:
  terraform-checks:
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    uses: evolve-platform/terraform-github-workflows/.github/workflows/dependabot-changie-v1.yaml@a7b03e3197bfdd5883f451854fce85375c2dc2e0 # v0.0.1
    secrets: inherit
