name: Module parity

on:
  push:
  workflow_dispatch:

jobs:
  parity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: ./scripts/parity.py check
